apiVersion: apps/v1            # Deployment API
kind: Deployment              # Resource type
metadata:
  name: my-deployment         # Deployment name
spec:
  replicas: 5                 # Number of pods
  selector:
    matchLabels:
      app: myapp              # Must match pod labels
  template:
    metadata:
      labels:
        app: myapp            # Pod label
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp          # matches Deployment pod label
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 80    # container port
  type: ClusterIP       # default (internal access)