apiVersion: apps/v1             
kind: Deployment                   
metadata:
  name: probe-demo   
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: probe-demo           
  template:
    metadata:
      labels:
        app: probe-demo            
    spec:
      containers:
      - name: probe-app            
        image: dockeritc778/pythonhealth  
        ports:
        - containerPort: 8080      


        resources:
          requests:
            cpu: "50m"             # Minimum CPU guaranteed (0.05 core)
            memory: "64Mi"         # Minimum memory guaranteed
          limits:
            cpu: "100m"            # Max CPU allowed (0.1 core)
            memory: "128Mi"        # Max memory allowed

  
        startupProbe:
          httpGet:
            path: /readiness    
            port: 8080
          periodSeconds: 5        
          failureThreshold: 10    
          timeoutSeconds: 2

      
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1

     
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1