apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - echo "Hello from NFS" >> /data/file.txt && sleep 3600
    volumeMounts:
    - name: nfs-storage
      mountPath: /data

  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc