apiVersion: apps/v1              # DaemonSet API
kind: DaemonSet                  # Resource type
metadata:
  name: my-daemonset             # Name
spec:
  selector:
    matchLabels:
      app: myapp                 # Must match pod labels
  template:
    metadata:
      labels:
        app: myapp               # Pod label
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80