apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-highmem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        vmtype: highmem
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80